language: csharp
dist: trusty
sudo: required
mono: none
dotnet: 1.0.4
script:
  - dotnet restore -s https://api.nuget.org/v3/index.json
  - dotnet test ./ASC.Tests/ASC.Tests.csproj
  - dotnet build
  email:
notifications:
  email:
    recipients:
    - trevorjedsmith@gmail.com
    - trevor_jed_smith@hotmail.com
    on_success: always
    on_failure: always